#!/bin/bash

## scATAC-pro           



#########################
## usage ####
#########################                                                                   

SOFT="scATAC-pro"
VERSION="1.1.0"

function usage {
    echo -e "usage : $SOFT -s STEP -i INPUT -c CONFIG [-o] [-h] [-v]"
    echo -e "Use option -h|--help for more information"
}

function help {
    usage;
    echo 
    echo "$SOFT $VERSION"
    echo "---------------"
    echo "OPTIONS"
    echo
    echo "   [-s|--step ANALYSIS_STEP] : run a analytic step (or combinatorial steps) of the $SOFT workflow, supportting steps:"
    echo "      demplx_fastq: perform demultiplexing
                           input: fastq files for both reads and index, separated by comma like:
                                  PE1_fastq,PE2_fastq,index1_fastq,inde2_fastq,index3_fastq...;
                                  differnet index will be embedded in the read name as: 
                                  @index1_index2_index3:original_read_name
                           output: demultiplexed fastq1 and fastq2 files "
    echo "      mapping: perform reads alignment
                         input: fastq files, separated by comma for each paired end
                         output: position sorted bam file, mapping qc stat and fragment.bed"
    echo "      call_peak: call peaks for aggregated data
                           input: BAM file path
                           output: peaks in bed file format"
    echo "      get_mtx: build raw peak by barcode matrix
                         input: features/peaks file path
                         output: sparse matrix in Matrix Market format"
    echo "      aggr_signal: generate aggregated signal, which can be upload to and view
                             in genome browser
                             input: require BAM file path
                             output: bw and bedgraph file"
    echo "      qc_per_barcode: quality control per barcode
                                input: fragment.txt file and feature/peak file, separated by comma
                                output: qc_per_barcode.summary"
    echo "      process: processing data - including dex_fastq, mapping, call_peak, get_mtx,
                            aggr_signal, qc_per_barcode abd call_cell
                            input: fastq files for both reads and index, separated by comma like:
                                   fastq1,fastq2,index_fastq1,index_fastq2, index_fastq3...; 
                            output: cell peak matrix and all intermediate results "
    echo "      process_no_dex: processing data without demultiplexing
                            input: demultiplexed fastq files for both reads and index, separated by comma like:
                                   fastq1,fastq2; 
                            output: cell peak matrix and all intermediate results "
    echo "      process_with_bam: processing from bam file
                            input: bam file for aggregated data 
                            output: cell peak matrix and all intermediate results "
    echo "      call_cell: cell calling
                           input: raw peak barcode sparse matrix file path
                           output: filtered peak by cell matrix"
    echo "      get_bam4Cells: extract bam file for cell barcodes and calculate mapping stats
                           input: bam file for all barcodes and barcodes.txt file, separeted by comma
                           output: bam file and mapping stats (optional) for cell barcodes"
    echo "      clustering: cell clustering
                           input: filtered peak by cell matrix file path
                           output: seurat objects with clustering label in the metadata (.rds file) and 
                                   barcodes with cluster labels (bed file)"
    echo "      motif_analysis: doing motif analysis
                           input: filtered peak by cell matrix file path
                           output: TF by cell matrix indicating TF accessibility (chromVAR object)"
    echo "      runDA: doing differential accessibility analysis
                           input: seurat_obj.rds path from clustering analysis
                           output: differential peaks in txt format saved at the same directory as seurat_obj.rds"
    echo "      runGO: doing GO analysis
                           input: result of runDA module (.txt file)
                           output: enriched GO terms in .xlsx saved at the same directory as the input file"
    echo "      runCicero: run cicero for calculating gene activity score and predicting interactions
                           input: seurat_obj.rds path from clustering analysis
                           output: gene activity in .rds format and predicted interactions in .txt format"
    echo "      split_bam: split bam file into different clusters
                           input: barcodes with cluster label (.txt file, outputed from clustering)
                           output: .bam (saved under downstream/CELL_CALLER/data_by_cluster), .bw, .bedgr                                                            aph (save under output/signal/) file for each cluster"
    echo "      footprint: doing footprinting analysis
                           input: bam files of two clusters, separated by comma like, bam1,bam2
                           output: footprint summary statistics (saved under output/downstream/CELL_CALLE                                                            R/footprinting/)"
    echo "      integrate: doing integration analysis for two ore more samples
                           input: bam files, separated by comma like, bam1,bam2
                           output: save all intemediate results under output/integrated/)"
    echo "      downstream: do all downstream analysis, including clustering, motif_analysis, 
                            split_bam (optional) and footprinting analysis (optional)
                            input: filtered matrix file path
                            output: all outputs from each step"
    echo "      report: generate report in html file
                        input: directory to output report
                        output: summary report in html format"
    echo "      convert10xbam: convert bam in 10x style to bam in scATAC-pro style 
                         input: bam file (position sorted) in 10x style
                         output: position sorted bam file in scATAC-pro style, mapping qc stat and fragment.bed"
    echo "      mergePeaks: merge different peaks (called from differnt samples or conditions) if the distance is
                            less than a given #basepairs (200 if not specified) 
                         input: peak files and a distance paramter separated by comma, like:
                                peakFile1,peakFile2,peakFile3,200
                         output: merged peaks saved in file output/peaks/merged.bed"
    echo "      reConstMtx: reconstruct peak-cell matrix given peak file, fragments.txt file, and barcodes.txt file 
                         input: differnt files separated by comma, like:
                                peakFilePath,fragmentFilePath,barcodesPath
                         output: a reconstructed peak-cell matrix saved under the same path as barcodes.txt file"
    echo "      visualize: interactively visualize the data through web browser
                         input: VisCello_obj directory (created by clustering module)
                         output: web browser pop up for interactively visualization"
    echo "   -i|--input INPUT : input data, different types of input data are required for different steps;"
    echo "   -c|--conf CONFIG : configuration file for parameters (if exists) for each step"
    echo "   [-o|--output_dir : folder to save results; sub-folder will be created automatically for each step"
    echo "   [-h|--help]: help"
    echo "   [-v|--version]: version"
    exit;
}

function version {
    echo -e "$SOFT version $VERSION"
    exit
}


function opts_error {
    echo -e "Error : invalid parameters !" >&2
    echo -e "Use $SOFT -h for help"
    exit
}

#####################
## Set PATHS and defaults
#####################

SOFT_PATH=`dirname $0`
ABS_SOFT_PATH=`cd "$SOFT_PATH"; pwd`
SCRIPTS_PATH="$ABS_SOFT_PATH/scripts"
CUR_PATH=$PWD

CLUSTER=0
MAKE_OPTS=""
STEP=""
INPUT=""
OUTPUT_DIR="output"
CONF="configure_user.txt"





#####################
## Inputs
#####################
if [ $# -lt 1 ]
then
    usage
    exit
fi

# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
      "--step")   set -- "$@" "-s" ;;
      "--input") set -- "$@" "-i" ;;
      "--conf")   set -- "$@" "-c" ;;
      "--output_dir")   set -- "$@" "-o" ;;
      "--help")   set -- "$@" "-h" ;;
      "--version")   set -- "$@" "-v" ;;
      *)        set -- "$@" "$arg"
  esac
done

while getopts ":s:i:c:o:vh" OPT
do
    case $OPT in
	s) STEP=$OPTARG;;
	i) INPUT=$OPTARG;;
	c) CONFIG=$OPTARG;;
	o) OUTPUT_DIR=$OPTARG ;;
	v) version ;;
	h) help ;;
	\?)
	     echo "Invalid option: -$OPTARG" >&2
	     usage
	     exit 1
	     ;;
	 :)
	     echo "Option -$OPTARG requires an argument." >&2
	     usage
	     exit 1
	     ;;
    esac
done



if [[ -z $INPUT || -z $CONFIG ]]; then
    usage
    exit
fi


################################ check valid STEPs #####
############################
AVAILABLE_STEP_ARRAY=("demplx_fastq" "trimming" "mapping" "mapping_qc" "aggr_signal" "call_peak" "recall_peak" "get_mtx" "qc_per_barcode" "call_cell" "get_bam4Cells" "clustering" "motif_analysis" "call_cnv" "runDA" "runGO" "runCicero" "split_bam" "footprint" "report" "process" "process_no_dex" "process_with_bam" "integrate" "downstream" "all" "integrate_seu" "convert10xbam" "mergePeaks" "reConstMtx", "visualize")


check_s=0
for i in ${AVAILABLE_STEP_ARRAY[@]}; do
	    if [[ "$i" = "$STEP" ]]; then check_s=1; fi
done


if [[ $check_s = 0 ]]; then die "Unknown STEP option (\"-s $s\"). Use $0 --help for usage information."; fi


############################
## make output_dir
############################




echo "Run scATAC-pro "${VERSION}



###################################################
##Run scATAC-pro
###################################################



declare -x OUTPUT_DIR
declare -x logDir

if [ "$STEP" = "integrate" ]; then
    OUTPUT_DIR=${OUTPUT_DIR}/integrated
fi

mkdir -p $OUTPUT_DIR
logDir=${OUTPUT_DIR}/logs
mkdir -p $logDir

###################################################
##Run scATAC-pro
###################################################

#make --file ${SCRIPTS_PATH}/Makefile INPUT_FILE=$INPUT OUTPUT_DIR=$OUTPUT_DIR $STEP 2>&1
config_sys=${ABS_SOFT_PATH}/configure_system.txt
make --file ${SCRIPTS_PATH}/Makefile INPUT_FILE=$INPUT CONFIG_FILE=$CONFIG CONFIG_SYS=$config_sys $STEP > ${logDir}/$STEP.log 2>&1



