#!/bin/bash

## scATAC-pro           



#########################
## usage ####
#########################                                                                   

SOFT="scATAC-pro"
VERSION="1.0.0"

function usage {
    echo -e "usage : $SOFT -s STEP -i INPUT -c CONFIG [-o] [-p] [-h] [-v]"
    echo -e "Use option -h|--help for more information"

    if [[ ! -e ${CONFIG} ]]; then
	echo "Error - configure file not detected."
	exit -1
    fi
}

function version {
    echo -e "$SOFT version $VERSION"
    exit
}


function opts_error {
    echo -e "Error : invalid parameters !" >&2
    echo -e "Use $SOFT -h for help"
    exit
}

#####################
## Set PATHS ##
#####################

SOFT_PATH=`dirname $0`
ABS_SOFT_PATH=`cd "$SOFT_PATH"; pwd`
SCRIPTS_PATH="$ABS_SOFT_PATH/scripts"
CUR_PATH=$PWD

CLUSTER=0
MAKE_OPTS=""
STEP=""
INPUT=""
OUTPUT_DIR="output"
CONF="configure.txt"





#####################
## Inputs
#####################
if [ $# -lt 1 ]
then
    usage
    exit
fi

# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
      "--step")   set -- "$@" "-s" ;;
      "--input") set -- "$@" "-i" ;;
      "--conf")   set -- "$@" "-c" ;;
      "--output_dir") set -- "$@" "-o" ;;
      "--parallel")   set -- "$@" "-p" ;;
      "--help")   set -- "$@" "-h" ;;
      "--version")   set -- "$@" "-v" ;;
      *)        set -- "$@" "$arg"
  esac
done

while getopts ":s:i:c:o:p:v:h" OPT
do
    case $OPT in
	s) STEP=$OPTARG;;
	i) INPUT=$OPTARG;;
	c) CONFIG=$OPTARG;;
	o) OUTPUT_DIR=$OPTARG;;
	p) CLUSTER=1 ;;
	v) version ;;
	h) help ;;
	\?)
	     echo "Invalid option: -$OPTARG" >&2
	     usage
	     exit 1
	     ;;
	 :)
	     echo "Option -$OPTARG requires an argument." >&2
	     usage
	     exit 1
	     ;;
    esac
done



if [[ -z $INPUT || -z $CONFIG ]]; then
    usage
    exit
fi


################################ check valid STEPs #####
############################
AVAILABLE_STEP_ARRAY=("demplx_fastq" "mapping" "filter_bam" "generate_signal" "call_peak" "get_peak_barcode_mat" "get_bin_barcode_mat" "filter_mat" "filtered_qc")
NEED_BAM_STEP_ARRAY=("filter_bam" "generate_signal" "get_cell_peak_mat" "get_cell_bin_mat" "filtered_qc")
NEED_FASTQ_STEP_ARRAY=("demplx_fastq mapping")

NEED_BAM=0
NEED_FASTQ=0

check_s=0
for i in ${AVAILABLE_STEP_ARRAY[@]}; do
	    if [[ "$i" == "$STEP" ]]; then check_s=1; fi
done


if [[ $check_s == 0 ]]; then die "Unknown STEP option (\"-s $s\"). Use $0 --help for usage information."; fi

for i in ${NEED_FASTQ_STEP_ARRAY[@]}; do
	    if [[ "$i" == "$STEP" ]]; then NEED_FASTQ=1; fi
done

for i in ${NEED_BAM_STEP_ARRAY[@]}; do
	    if [[ "$i" == "$STEP" ]]; then NEED_BAM=1; fi
done

############################
## make output_dir
############################
mkdir -p $OUTPUT_DIR


#cd $OUTPUT_DIR

if [ $CLUSTER == 0 ]; then
    echo "Run scATAC-pro "${VERSION}

fi



###################################################
## declare global variables, whose values will be 
## provided through user specified configure file
###################################################
declare -x BWA_PATH
declare -x GENOME_FASTA
declare -x PYTHON_PATH
declare -x SAMTOOLS_PATH
declare -x SAMPLE_PREFIX
declare -x MAPQ
declare -x MACS2_PATH
declare -x MACS2_OPTS
declare -x BEDTOOLS_PATH
declare -x PERL_PATH
declare -x R_PATH
declare -x DEEPTOOLS_PATH


source $CONFIG



###################################################
##Run scATAC-pro
###################################################

make --file ${SCRIPTS_PATH}/Makefile INPUT_FILE=$INPUT OUTPUT_DIR=$OUTPUT_DIR $STEP 2>&1



